DROP TABLE MOVIE;

CREATE TABLE MOVIE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR2(255) NOT NULL DEFAULT '',
  GENRE VARCHAR2(255) NOT NULL DEFAULT '',
  RELEASE NUMBER(10,0) DEFAULT NULL,
  RATING FLOAT DEFAULT NULL,
  PRIMARY KEY (ID));

  DROP SEQUENCE hibernate_sequence;

  CREATE SEQUENCE hibernate_sequence;